### ISSUE TITLE
feature: support for adding worker new node easily without impacting existing cluster.

### ISSUE THREAD

**Issue by shan100github** [lablabs/ansible-role-rke2#100]
### Summary

While trying to add a new worker node to the existing HA cluster, it restarts the RKE2 services of all existing master and worker nodes. Also, it takes a long time to complete the ansible execution which can be improved.

While adding new nodes I have commented "- name: Wait for remaining nodes to be ready" in remaining_nodes.yml, and also commented "Rolling restart" task from "main.yml".
This improved start of services in the newly added worker node.

We can have parameters to support adding new workers to the existing cluster?

Question: Even during new server deployment do we need to have "- name: Wait for remaining nodes to be ready" in remaining_nodes.yml? 

### Issue Type

Feature Idea

**Comment by newbenji** [comment]
I think as with issue #91 some cleanup needs to be done, with register changes etc and restart only if changes.
ex is download of rke2 to localhost not a change that should trigger an change on the node 
can try look into something in next weekend

**Comment by MonolithProjects** [comment]
This is no longer an issue. Closing...
