### ISSUE TITLE
feature: Support for cni: none for cilium cli install's 

### ISSUE THREAD

**Issue by rykelley** [lablabs/ansible-role-rke2#117]
### Summary

The best way to install cilium is to install rke2 with no cni, and then use the cilium cli to install it but then the node will show a status of NotReady, you have checked for Status " Ready " on the pod network. I have tried commenting on this check out, and also changing the stdout to "NotReady" but still does not work. Am I missing 

### Issue Type

Feature Idea

**Comment by davidjveer** [comment]
We have the same issue in our testing.

**Comment by lukapetrovic-git** [comment]
Added in #169, submitted for review
