### ISSUE TITLE
feature: use template mode instend of copy in the Copy Custom Manifests task

### ISSUE THREAD

**Issue by hamatuni** [lablabs/ansible-role-rke2#118]
### Summary

The role currently [uses](https://github.com/lablabs/ansible-role-rke2/blob/557a346ae8ef788dba557c6503425172cd897485/tasks/rke2.yml#L112) Ansible [copy](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_mo) module to copy Custom Manifests. With this module we cannot use variables in the files/manifests.

if we need variable interpolation in copied files, we probably need to use the [ansible.builtin.template](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html) module.

The main Idea is replace copy module with the template

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Feature merged in #124
