### ISSUE TITLE
bug: [BREAKING] disable_kube_proxy is commented in default/main.yaml

### ISSUE THREAD

**Issue by HaXX49** [lablabs/ansible-role-rke2#143]
### Summary

In the default values in default/main.yaml, disable_kube_proxy: true is commented. It breaks all stages concerning the first node as the variable is called upon.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/cloudadm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cloudadm/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/cloudadm/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cloudadm/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

Run the role without explicitly assigning a value to diasable_kube_proxy.

### Expected Results

The role should run smoothly with disable_kube_proxy set to true

### Actual Results

```console
The role breaks when it calls the variable during a check.
```

**Comment by MonolithProjects** [comment]
Thanks @HaXX49  for reporting this issue. Fix is on the way.
