### ISSUE TITLE
Node labels

### ISSUE THREAD

**Issue by alefr** [lablabs/ansible-role-rke2#16]
Hi,

Thank you for a great role, made my life easier when migrating from RKE1 to RKE2.
First looking into rancherd but then moving back to RKE2 I was happy when I found this role, so thank you for that ☺️

I have a question regarding node labels.
I found that it was possible to add node labels using the var `k8s_node_label`. 

My question is regarding the documentation for the labels (or rather the `k8s_node_label` var). 
I haven't seen any documentation for it. I found it when looking through the source files (to see if it was possible to add nodes).

The missing documentation makes me a bit worried that it's not ready for use?
Is there a reason for me not to use it? Or is it that it just hasn't been documented (or did I miss it somewhere)?

**Comment by MonolithProjects** [comment]
Hey @alefr , thanks for letting us know about this. Actually the variable is fully ready to be used. I just somehow forgot to document it. Will fix that...
