### ISSUE TITLE
feature: Upgrade

### ISSUE THREAD

**Issue by ninnube** [lablabs/ansible-role-rke2#162]
### Summary

Dear,
Can I upgrade the Kubernetes version or update the installation configurations by running Ansible? Will my data be deleted?
Thanks.

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Hi @ninnube. Yes, You can upgrade your RKE2 Kubernetes cluster by changing `rke2_version` variable and re-running the Ansible.
