### ISSUE TITLE
bug: when bootstrapping cluster with kube-vip, role fails on "Wait for the first server be ready"

### ISSUE THREAD

**Issue by paulfantom** [lablabs/ansible-role-rke2#172]
### Summary

When running role on a fresh set of VMs with kube-vip as a VIP controller and `rke2_api_ip` set to that VIP, role fails on

```
TASK [lablabs.rke2 : Wait for the first server be ready - with CNI]
```

I believe this is because `kube-vip` manifests are put on disk AFTER running tasks from `first_server.yml`. If [those 2 sections](https://github.com/lablabs/ansible-role-rke2/blob/main/tasks/main.yml#L24-L36) could be swapped, it would most likely solve the issue.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.14.9]
  config file = None
  configured module search path = ['/home/paulfantom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/paulfantom/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

Start a new cluster with the following variables

```yaml (paste below)
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: true

rke2_api_ip: "<SOME_IP_NOT_ASSIGNED_TO_ANY_NODE>"
```

### Expected Results

I expect the playbook to run properly

### Actual Results

```console
Role fails on


TASK [lablabs.rke2 : Wait for the first server be ready - with CNI] *************************************************************************************************
FAILED - RETRYING: 
```
```

**Comment by MonolithProjects** [comment]
Fixed in https://github.com/lablabs/ansible-role-rke2/issues/173
