### ISSUE TITLE
feature: update kubevip templated to support additional environment variables.

### ISSUE THREAD

**Issue by shan100github** [lablabs/ansible-role-rke2#179]
### Summary

KubeVIP supports the following additional parameters in kube-vip daemon set but looks like those are not in templates/kube-vip/kube-vip.yml.j2 
https://kube-vip.io/docs/installation/flags/
![Screenshot 2023-11-30 at 12 58 38](https://github.com/lablabs/ansible-role-rke2/assets/13979716/298fdb15-bdcb-4219-903e-5ad8eb991c9c)

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Issue fixed in #185
