### ISSUE TITLE
Error templating

### ISSUE THREAD

**Issue by max-rh** [lablabs/ansible-role-rke2#18]
I am having this error while running the playbook.

`{"msg": "The conditional check 'inventory_hostname is in groups.masters' failed. The error was: template error while templating string: expected token 'end of statement block', got '.'. String: {% if inventory_hostname is in groups.masters %} True {% else %} False {% endif %}\n\nThe error appears to be in '/root/.ansible/roles/lablabs.rke2/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Keepalived when HA mode is enabled\n  ^ here\n"}`

I am using the latest ansible version; and I have tried an older version as well, any idea whats going on here ?

**Comment by MonolithProjects** [comment]
Hi @max-rh, it looks like there something is wrong with your inventory. Could you please share it?

**Comment by MonolithProjects** [comment]
Hmm i was unable to reproduce this issue (tested on Ansible 2.12.1 and Jinja2 3.0.3 and also Jinja2 2.11.3) and for me it did work fine, i found one error in the condition statement which could cause this. Will fix it...

**Comment by max-rh** [comment]
Thanks; testing your branch right now :)

**Comment by max-rh** [comment]
Thanks. Got it working on the develop branch. 

But got stuck on another templating error:

`{"msg": "The conditional check 'rke2_custom_registry is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if rke2_custom_registry is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/root/.ansible/roles/lablabs.rke2/tasks/first_server.yml': line 19, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy Containerd Registry Configuration file\n  ^ here\n"}`

**Comment by MonolithProjects** [comment]
Hi @max-rh, sorry i missed your comment. I went trough all task conditionals and corrected them in release 1.2.2. You can try if it works for you.

**Comment by max-rh** [comment]
Thanks for the response ; I am building another cluster today; will give it a try

**Comment by max-rh** [comment]
Hi @MonolithProjects 
Tried the playbook again yesterday; worked better than last time; the only error i got templating was from this line 

https://github.com/lablabs/ansible-role-rke2/blob/main/tasks/first_server.yml#L26

I modified it to rke2_custom_registry == "true" and then it ran smoothly.

**Comment by MonolithProjects** [comment]
Hi @max-rh yes it seems like i missed that one. I fixed that and currently the fix is pushed in `develop` branch and will be released soon.

**Comment by MonolithProjects** [comment]
BTW thanks for help with catching all those bugs!

**Comment by max-rh** [comment]
no problem; thanks for being cooperative :)
