### ISSUE TITLE
feature: Add debug mode

### ISSUE THREAD

**Issue by Tosta-Mista** [lablabs/ansible-role-rke2#181]
### Summary

Hello, 

From time to time I have to set up a rancher in a complicated environment and It would be great if it was possible to enable debug mode during the cluster set up.  

This is why I am submitting my PR to you in order to be able to do this. 

Thank you very much for this role which is very useful to me. 

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Fixed in #182
