### ISSUE TITLE
Noob Question: After Cluster creation where is the config file?

### ISSUE THREAD

**Issue by NikoKS** [lablabs/ansible-role-rke2#200]
I understand that it's going to be in /etc/rancher/rke2/rke2.yaml in the master node, but do I need to copy it manually to the ansible server?

**Comment by MonolithProjects** [comment]
Hi @NikoKS , you can set the variable `rke2_download_kubeconf: true` and the role will copy it for you to your Ansible server. For more info see the default vars https://github.com/lablabs/ansible-role-rke2/blob/f323342a33a0b71c0a65ca1a520eb1bec98abf47/defaults/main.yml#L203-L209
