### ISSUE TITLE
feature: add cilium helm chart 

### ISSUE THREAD

**Issue by villadalmine** [lablabs/ansible-role-rke2#236]
### Summary

I want to add support to deploy cilium with extra values with helmchart-config

### Issue Type

Feature Idea

**Comment by hoangphuocbk** [comment]
You can create your customized manifest files as the document (https://docs.rke2.io/helm), then declare these files to `rke2_custom_manifests`

**Comment by villadalmine** [comment]
So the PR I created it is not needed

**Comment by villadalmine** [comment]
I think there is one difference between using rke2_custom_manifest and use rke2 helmchartconfig where are maintained by rke2


The helmchart integration in rke2 it is about the crd helmchart for external helmchart and the helmchartconfig for rke2 helmchart . What I m trying to add and request is kind of support to add more rke2 helmchartconfig in the bootstrapping

**Comment by MonolithProjects** [comment]
Hi @villadalmine, @hoangphuocbk is right. You can just use `rke2_custom_manifests` which is being used in the code much earlier stage as your addition. You can see it here in the main file https://github.com/lablabs/ansible-role-rke2/blob/f733dbb913a148d19be5392b345e2d3102b1d009/tasks/main.yml#L11-L12 and then here https://github.com/lablabs/ansible-role-rke2/blob/f733dbb913a148d19be5392b345e2d3102b1d009/tasks/rke2.yml#L142-L150

**Comment by villadalmine** [comment]
Ok, more standard , you can close it, and keep doing it, it is amazing implementation
