### ISSUE TITLE
bug: Can not provision cluster 

### ISSUE THREAD

**Issue by hoangphuocbk** [lablabs/ansible-role-rke2#253]
### Summary

after this commit https://github.com/lablabs/ansible-role-rke2/pull/246/files
```
{% if rke2_bind_address is defined %}
bind-address: {{ rke2_bind_address }}
{% endif %}
```
the rke2 cluster can not provision when we use kube-vip, because `bind-address` should be listened on 0.0.0.0 rather specific one on server nodes.

### Issue Type

Bug Report

### Ansible Version

```console
abc
```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

abc

### Actual Results

```console
abc
```

**Comment by MonolithProjects** [comment]
Hi @hoangphuocbk, this is optional. You don't have to use this variable. If it's not set, the RKE2 default value for `bind-address` is `0.0.0.0`
