### ISSUE TITLE
feature: "Introduce in ansible-role-rke2 the ability to configure etcd snapshots on S3."

### ISSUE THREAD

**Issue by neni84** [lablabs/ansible-role-rke2#284]
### Summary

Ability to configure recurring snapshots on S3, allowing the configuration, for examples, of the following values:
etcd-s3: true
etcd-snapshot-schedule-cron: '0 */12 * * *'
etcd-snapshot-retention: 5
etcd-s3-bucket: etcd-backup
etcd-s3-access-key: myuser
etcd-s3-secret-key: mykey
etcd-s3-folder: myfolder
etcd-s3-endpoint: mys3.s3.svc.cluster.local
etcd-s3-region: mt-region
etcd-s3-skip-ssl-verify: false

### Issue Type

Feature Idea

**Comment by maxisam** [comment]
https://github.com/lablabs/ansible-role-rke2/blob/859a27f112add823280e9609a2c0056c0f30247f/README.md?plain=1#L224-L247
  have you try this?

**Comment by maxisam** [comment]
https://github.com/lablabs/ansible-role-rke2/issues/104

**Comment by neni84** [comment]
Ok, I hadn't noticed this possibility, I'll try to use this conf to configure it:

# (Optional) Additional RKE2 server configuration options
# You could find the flags at https://docs.rke2.io/reference/server_config
# rke2_server_options:

Thanks.
E

**Comment by neni84** [comment]
I confirm that with a conf similar to this it works.
    rke2_server_options:
      - "etcd-s3: true"
      - "etcd-s3-endpoint: "
      - "etcd-s3-access-key: "
      - "etcd-s3-secret-key: "
      - "etcd-s3-bucket: rke2-cluster01"
      - "etcd-s3-region: "
      - "etcd-s3-folder: rke2-cluster01-etcd"
      - "etcd-snapshot-retention: 12"
  roles:
    - role: lablabs.rke2
