### ISSUE TITLE
bug: Custom Manifests doesn't work

### ISSUE THREAD

**Issue by maxisam** [lablabs/ansible-role-rke2#285]
### Summary

I believe the issue is here

https://github.com/lablabs/ansible-role-rke2/blob/859a27f112add823280e9609a2c0056c0f30247f/tasks/rke2.yml#L234-L242

This part expects rke2_custom_manifests  as a list

but this part expects rke2_custom_manifests  as a string value

https://github.com/lablabs/ansible-role-rke2/blob/859a27f112add823280e9609a2c0056c0f30247f/tasks/rke2.yml#L252C1-L262

And I don't think we need both. 

This role works fine before 1.38.0, the issue starts from https://github.com/lablabs/ansible-role-rke2/pull/260

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.17.7]
  config file = None
  configured module search path = ['/home/saml/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/saml/miniforge3/lib/python3.10/site-packages/ansible
  ansible collection location = /home/saml/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/saml/miniforge3/bin/ansible
  python version = 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (/home/saml/miniforge3/bin/python3.10)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

whenever you have rke2_custom_manifests.

### Expected Results

it should work

### Actual Results

```console
it throws error like it can't find any file when using it like a list.

@MonolithProjects if you think it is ok I can make a PR to remove https://github.com/lablabs/ansible-role-rke2/blob/859a27f112add823280e9609a2c0056c0f30247f/tasks/rke2.yml#L234-L242
```

**Comment by MonolithProjects** [comment]
@maxisam yes that code ended up there by a mistake. My bad. Feel free to propose a fix. Thx!
