### ISSUE TITLE
Revoke kubeconfig file and re-create the new one

### ISSUE THREAD

**Issue by hdong69** [lablabs/ansible-role-rke2#293]
Hi team,

Currently, i want to revoke a kubeconfig file for some reason in a k8s installed by rke2. I did follow the [doc](https://docs.rke2.io/security/certificates#rotating-self-signed-ca-certificates) to rotate the CA certificate but the old kubeconfig file still works.

Please support me

**Comment by MonolithProjects** [comment]
Hi @hdong69 , i don't think this github project is a right place for your question. Try it here https://github.com/rancher/rke2/discussions
