### ISSUE TITLE
running the playbook after rebooting the nodes

### ISSUE THREAD

**Issue by max-rh** [lablabs/ansible-role-rke2#30]
When I tried running the playbook again on the cluster to increase the number of nodes; i faced an issue where the playbook looks for /tmp/rke2.sh in the old nodes; but my cluster nodes rebooted since they were initialized; so this is what i am getting :

`{"changed": false, "msg": "file (/tmp/rke2.sh) is absent, cannot continue", "path": "/tmp/rke2.sh", "state": "absent"}`

any idea how to bypass this ?

**Comment by Sea-you** [comment]
I think the download path should be changed to `/var/tmp` so it preserves between reboots.

**Comment by MonolithProjects** [comment]
Hi @max-rh. @Sea-you is right. Unfortunately the path to the script is hardcoded. But https://github.com/lablabs/ansible-role-rke2/pull/33 will fix it.

**Comment by max-rh** [comment]
Thanks :)

**Comment by max-rh** [comment]
Thanks for the new feature to customize the installation scripts location.

But is there anyway to bypass this for an already running cluster? since the script is already gone from /tmp

**Comment by MonolithProjects** [comment]
Hmm that is strage as the task which is executing `rke2.sh` is running after the task which downloads the script. So technically you should not see this issue even if you were using `/tmp` and rebooted your node. But will test it bit later...
