### ISSUE TITLE
Question about support of haproxy inplace of keepalived

### ISSUE THREAD

**Issue by rverma-nsl** [lablabs/ansible-role-rke2#37]
We are currently running kubespray in ha with haproxy. Is it possible to do same here?
I saw that keepalived is mandatory in ha-mode

**Comment by MonolithProjects** [comment]
hi @rverma-nsl , yes currently it is mandatory . But i am planning to make the keepalived optional so users can use some pre configured LB.

**Comment by MonolithProjects** [comment]
Resolved in https://github.com/lablabs/ansible-role-rke2/pull/40
