### ISSUE TITLE
Master nodes fail to join cluster if multiple nodes are joined concurrently

### ISSUE THREAD

**Issue by GabriFedi97** [lablabs/ansible-role-rke2#38]
If multiple master node servers try to join the cluster concurrently, the rke2-server service fails on one or more master nodes, with the following error:
"Failed to start Rancher Kubernetes Engine v2 (server)."
When the rke2-service fails on a host, Ansible considers the failure as "Fatal" and stops executing the following tasks on the respective host.

![image](https://user-images.githubusercontent.com/91485518/152190377-15ce180b-eb77-41f7-bf37-32ce6c1d6d3c.png)

The results is that the node will then join the cluster, because systemd keep restarting the service until the activation succeeds, but the playbook stops executing the tasks on that particular host.

I resolved this issue adding a "retry" on the task "Start RKE2 service on the rest of the nodes" in the file "remaining_nodes.yml".
Here's the commit on my forked project: https://github.com/GabriFedi97/ansible-role-rke2/commit/70abe0d5241aa4bc11387e239f2e7f94cd4fa9e3

There is an issue on rke2 that explains the problem: https://github.com/rancher/rke2/issues/349

**Comment by MonolithProjects** [comment]
Cool, thanks @GabriFedi97 for info. I will check it ...

**Comment by MonolithProjects** [comment]
Fixed in https://github.com/lablabs/ansible-role-rke2/pull/40
