### ISSUE TITLE
Use a custom rke2 config.yaml file instead of template

### ISSUE THREAD

**Issue by Yannis100** [lablabs/ansible-role-rke2#44]
Hello,

Thanks for the role, working great !

I have a full config file for RKE2 server with multiple parameters (etcd-s3)
I tried to used it directly with
`rke2_server_options: "{{ lookup('file', '../config.yml') | from_yaml }}"`
But unfortunately it only writes the keys and not the values in the file generated from template

It would be marvellous to use own config file

**Comment by MonolithProjects** [comment]
Hi @Yannis100, currently the options `rke2_server_options` and `rke2_agent_options` accepts a list of strings containing the key and value separated by a colon. So, in your case you have to provide a yaml which looks something like this:
```
- "key1: value1"
- "key2: value2"
```
