### ISSUE TITLE
Add restore snapshot functionnality

### ISSUE THREAD

**Issue by olivier-univ-tours** [lablabs/ansible-role-rke2#48]
Hello,

First of all, thank you for this great work ! I love it !
May I suggest a new feature ? 
I would be very interested by an option to restore an etcd snapshot at installation time. 
I mean : 
 - deploy rke2 on first node, 
 - stop rke2-server on first node,
 - run "rke2 server --cluster-reset --cluster-reset-restore-path=<PATH-TO-SNAPSHOT>", with "<PATH-TO-SNAPSHOT>" as an ansible variable, 
 - start rke2-server on first node,
 - deploy rke2 on remaining nodes

Do you think it could be possible ? 

Best regards,

Olivier

**Comment by MonolithProjects** [comment]
Hi @olivier-univ-tours , thanks for this idea. You can find it now in release [1.14.0](https://github.com/lablabs/ansible-role-rke2/releases/tag/1.14.0)
