### ISSUE TITLE
support that /usr is mounted readonly

### ISSUE THREAD

**Issue by newbenji** [lablabs/ansible-role-rke2#70]
At the moment when checking for existing version it uses the hardcoded path /usr/local/bin/rke2 in the task rke2.yaml
if you look at the install script from get.rke2.io it will change target if the /usr is mounted RO
    # --- install tarball to /usr/local by default, except if /usr/local is on a separate partition or is read-only
    # --- in which case we go into /opt/rke2.

So the task for rke2 should be able to handle another location also.

**Comment by MonolithProjects** [comment]
Fixed in #71
