### ISSUE TITLE
feature: support CIS security hardening guides

### ISSUE THREAD

**Issue by bsecker** [lablabs/ansible-role-rke2#86]
### Summary

Hey, I've tried out this role and am already a fan of it over [Rancher's role](https://github.com/rancherfederal/rke2-ansible) as it is published on ansible-galaxy, which [doesn't seem to be on the roadmap for that repo](https://github.com/rancherfederal/rke2-ansible/issues/68). 

One thing I'd love is support for running CIS hardening as part of [RKE2 Security Hardening guide](https://docs.rke2.io/security/hardening_guide/). It's included in the rancherfederal repo [here](https://github.com/rancherfederal/rke2-ansible/blob/main/roles/rke2_common/tasks/cis-hardening.yml). 

I can add the following as a var:

```
rke2_server_options:
  - "profile: cis-1.6"
```

But I get the following error following the logs:

```
Jun 28 04:12:21 [HOSTNAME] sh[90630]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Jun 28 04:12:22 [HOSTNAME]  rke2[90634]: time="2022-06-28T04:12:22Z" level=fatal msg="missing required: user: unknown user etcd\nmissing required: group: unknown group etcd\ninvalid kernel parameter value vm.overcommit_memory=0 - expected 1\ninvalid kernel parameter value kernel.panic=0 - expected 10\ninvalid kernel parameter value kernel.panic_on_oops=0 - expected 1\n"
Jun 28 04:12:22 [HOSTNAME]  systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 28 04:12:22 [HOSTNAME]  systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Jun 28 04:12:22 [HOSTNAME]  systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
```

which is because it's failing in the CIS checks, as noted from the docs:

> Checks that host-level requirements have been met. If they haven't, RKE2 will exit with a fatal error describing the unmet requirements.

Side note: what is the background of this role? Was it created in parallel/independently of the `rancherfederal` repo?

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Hi @bsecker , sorry for late response. I implemented CIS Host-level hardening in release [1.18.0](https://github.com/lablabs/ansible-role-rke2/tree/1.18.0)
 There is a new variable called `rke2_cis_profile` where you can set the cis profile.

And to your question - this Ansible Role is independent ;)
