### ISSUE TITLE
feature: Rollout restart after /etc/rancher/rke2/config.yaml changed 

### ISSUE THREAD

**Issue by intonet** [lablabs/ansible-role-rke2#91]
### Summary

Changed made in /etc/rancher/rke2/config.yaml need restart. 
ie added tls-san, changed network plugin or cluster-cidr. 

### Issue Type

Feature Idea

**Comment by jakuzure** [comment]
same thing for changes regarding a custom registry, so /etc/rancher/rke2/registries.yaml
those only become active after rke2-{agent,server} was restarted

**Comment by viq** [comment]
Should be solved by https://github.com/lablabs/ansible-role-rke2/pull/113
